#!/bin/bash

docker run \
    -d \
    -v $(pwd)/messenger_blobs.json:/messenger_blobs.json \
    -v $(pwd)/api_credentials.json:/api_credentials.json \
    -v $(pwd)/logs:/logs \
    maxholloway/dydx-alerts:latest
